import Link from 'next/link';
import './layout.css';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      {/* <style>
        @import
        url(`https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap`);
      </style> */}
      <body>
        <main className='layout-container'>
          <nav className='layout-container__nav'>
            <Link className='layout-container__link' href='/'>Home</Link>
            <Link className='layout-container__link' href='/dashboard'>Dashboard</Link>
          </nav>
        </main>
        {children}
      </body>
    </html>
  );
}





